export const ALL_IMAGES_REUEST = "ALL_IMAGES_REUEST"
export const ALL_IMAGES_SUCESS = "ALL_IMAGES_SUCESS"
export const ALL_IMAGES_FAIL = "ALL_IMAGES_FAIL"


export const ALL_IMAGES_DETAILS_REUEST = "ALL_IMAGES_DETAILS_REUEST"
export const ALL_IMAGES_DETAILS_SUCESS = "ALL_IMAGES_DETAILS_SUCESS"
export const ALL_IMAGES_DETAIL_FAIL = "ALL_IMAGES_DETAIL_FAIL"
export const NEW_PRODUCT_RESET    = "NEW_PRODUCT_RESET";

export const UPLOAD_IMAGE_REQUEST =  "UPLOAD_IMAGE_REQUEST"
export const UPLOAD_IMAGE_SUCCESS =  "UPLOAD_IMAGE_SUCCESS"
export const UPLOAD_IMAGE_FAIL =  "UPLOAD_IMAGE_FAIL"

export const NEW_REVIEW_REQUEST =  "NEW_REVIEW_REQUEST"
export const NEW_REVIEW_SUCCESS =  "NEW_REVIEW_SUCCESS"
export const NEW_REVIEW_FAIL =  "NEW_REVIEW_FAIL"
export const NEW_REVIEW_RESET =  "NEW_REVIEW_RESET"

export const NEW_LIKE_REQUEST =  "NEW_RLIKE_REQUEST"
export const NEW_LIKE_SUCCESS =  "NEW_RLIKE_SUCCESS"
export const NEW_LIKE_FAIL =  "NEW_LIKE_FAIL"
export const NEW_LIKE_RESET =  "NEW_REVLIKE_RESET"



export const ADMIN_IMAGE_REQUEST =  "ADMIN_IMAGE_REQUEST"
export const ADMIN_IMAGE_SUCCESS =  "ADMIN_IMAGE_SUCCESS"
export const ADMIN_IMAGE_FAIL =  "ADMIN_IMAGE_FAIL"


export const ADMIN_DELETE_IMAGE_REQUEST =  "ADMIN_DELETE_IMAGE_REQUEST"
export const ADMIN_DELETE_IMAGE_SUCCESS =  "ADMIN_DELETE_IMAGE_SUCCESS"
export const ADMIN_DELETE_IMAGE_FAIL =  "ADMIN_DELETE_IMAGE_FAIL"
export const ADMIN_DELETE_IMAGE_RESET =  "ADMIN_DELETE_IMAGE_RESET"











export const CLEAR_ERRORS = "CLEAR_ERRORS"
