export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCESS = "LOGIN_SUCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"


export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCESS = "REGISTER_SUCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"


export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_SUCESS = "LOAD_USER_SUCESS"
export const LOAD_USER_FAIL = "LOAD_USER_FAIL"

export const ADMIN_USER_REQUEST = "ADMIN_USER_REQUEST"
export const ADMIN_USER_SUCESS = "ADMIN_USER_SUCESS"
export const ADMIN_USER_FAIL = "ADMIN_USER_FAIL"

export const ADMIN_DELETE_USER_REQUEST = "ADMIN_DELETE_USER_REQUEST"
export const ADMIN_DELETE_USER_SUCESS = "ADMIN_DELETE_USER_SUCESS"
export const ADMIN_DELETE_USER_FAIL = "ADMIN_DELETE_USER_FAIL"
export const ADMIN_DELETE_USER_RESET = "ADMIN_DELETE_USER_RESET"

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST"
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS"
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL"
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET"

export const CLEAR_ERRORS = "CLEAR_ERRORS"
